name: 'Publish application'

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/README.md'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet: ['6.0', '7.0', '8.0']
    steps:
        # Checkout the code
        - uses: actions/checkout@v4

        # Install .NET Core SDK
        - name: Setup .NET Core
          uses: actions/setup-dotnet@v3.2.0
          with:
            dotnet-version: ${{ matrix.dotnet }}

        # Run tests
        - name: Test
          run: dotnet test

        # Generate the website
        - name: Publish
          run: dotnet publish samples/KristofferStrube.Blazor.Popper.Samples/KristofferStrube.Blazor.Popper.Samples.csproj --configuration Release --output build

        # Publish the website
        - name: GitHub Pages action
          if: ${{ github.ref == 'refs/heads/main' }} # Publish only when the push is on master
          uses: peaceiris/actions-gh-pages@v3.9.3
          with:
            github_token: ${{ secrets.PUBLISH_TOKEN }}
            publish_branch: gh-pages
            publish_dir: build/wwwroot
            allow_empty_commit: false
            keep_files: false
            force_orphan: true
